---------------------------------------
Channel
---------------------------------------
	# interface Channel extends ShutdownNotifier, AutoCloseable

---------------------------------------
static
---------------------------------------


---------------------------------------
this
---------------------------------------
	public abstract void close()
	public abstract void close(int arg0, String arg1)
	public abstract void abort()
	public abstract void abort(int arg0, String arg1)
	public abstract DeclareOk queueDeclarePassive(String arg0)
	public abstract void clearConfirmListeners()
	public abstract void addConfirmListener(ConfirmListener arg0)
	public abstract ConfirmListener addConfirmListener(ConfirmCallback arg0, ConfirmCallback arg1)
	public abstract void setDefaultConsumer(Consumer arg0)
	public abstract void addReturnListener(ReturnListener arg0)
	public abstract ReturnListener addReturnListener(ReturnCallback arg0)
	public abstract Consumer getDefaultConsumer()
	public abstract void exchangeBindNoWait(String arg0, String arg1, String arg2, Map arg3)
	public abstract void exchangeDeclareNoWait(String arg0, String arg1, boolean arg2, boolean arg3, boolean arg4, Map arg5)
	public abstract void exchangeDeclareNoWait(String arg0, BuiltinExchangeType arg1, boolean arg2, boolean arg3, boolean arg4, Map arg5)
	public abstract void clearReturnListeners()
	public abstract void queueDeclareNoWait(String arg0, boolean arg1, boolean arg2, boolean arg3, Map arg4)
	public abstract boolean removeConfirmListener(ConfirmListener arg0)
	public abstract DeclareOk exchangeDeclarePassive(String arg0)
	public abstract void exchangeDeleteNoWait(String arg0, boolean arg1)
	public abstract void exchangeUnbindNoWait(String arg0, String arg1, String arg2, Map arg3)
	public abstract boolean removeReturnListener(ReturnListener arg0)
	public abstract DeclareOk queueDeclare(String arg0, boolean arg1, boolean arg2, boolean arg3, Map arg4)
	public abstract DeclareOk queueDeclare()
	public abstract DeleteOk queueDelete(String arg0)
	public abstract DeleteOk queueDelete(String arg0, boolean arg1, boolean arg2)
	public abstract void basicQos(int arg0, boolean arg1)
	public abstract void basicQos(int arg0, int arg1, boolean arg2)
	public abstract void basicQos(int arg0)
	public abstract BindOk exchangeBind(String arg0, String arg1, String arg2)
	public abstract BindOk exchangeBind(String arg0, String arg1, String arg2, Map arg3)
	public abstract UnbindOk exchangeUnbind(String arg0, String arg1, String arg2, Map arg3)
	public abstract UnbindOk exchangeUnbind(String arg0, String arg1, String arg2)
	public abstract BindOk queueBind(String arg0, String arg1, String arg2, Map arg3)
	public abstract BindOk queueBind(String arg0, String arg1, String arg2)
	public abstract void queueBindNoWait(String arg0, String arg1, String arg2, Map arg3)
	public abstract UnbindOk queueUnbind(String arg0, String arg1, String arg2, Map arg3)
	public abstract UnbindOk queueUnbind(String arg0, String arg1, String arg2)
	public abstract PurgeOk queuePurge(String arg0)
	public abstract int getChannelNumber()
	public abstract void basicPublish(String arg0, String arg1, boolean arg2, boolean arg3, BasicProperties arg4, byte[] arg5)
	public abstract void basicPublish(String arg0, String arg1, BasicProperties arg2, byte[] arg3)
	public abstract void basicPublish(String arg0, String arg1, boolean arg2, BasicProperties arg3, byte[] arg4)
	public abstract DeleteOk exchangeDelete(String arg0)
	public abstract DeleteOk exchangeDelete(String arg0, boolean arg1)
	public abstract GetResponse basicGet(String arg0, boolean arg1)
	public abstract void basicAck(long arg0, boolean arg1)
	public abstract void basicNack(long arg0, boolean arg1, boolean arg2)
	public abstract Connection getConnection()
	public abstract DeclareOk exchangeDeclare(String arg0, String arg1)
	public abstract DeclareOk exchangeDeclare(String arg0, String arg1, boolean arg2, boolean arg3, Map arg4)
	public abstract DeclareOk exchangeDeclare(String arg0, BuiltinExchangeType arg1, boolean arg2, boolean arg3, Map arg4)
	public abstract DeclareOk exchangeDeclare(String arg0, String arg1, boolean arg2, boolean arg3, boolean arg4, Map arg5)
	public abstract DeclareOk exchangeDeclare(String arg0, BuiltinExchangeType arg1, boolean arg2, boolean arg3, boolean arg4, Map arg5)
	public abstract DeclareOk exchangeDeclare(String arg0, BuiltinExchangeType arg1)
	public abstract DeclareOk exchangeDeclare(String arg0, String arg1, boolean arg2)
	public abstract DeclareOk exchangeDeclare(String arg0, BuiltinExchangeType arg1, boolean arg2)
	public abstract void basicCancel(String arg0)
	public abstract Command rpc(Method arg0)
	public abstract void asyncRpc(Method arg0)
	public abstract void basicReject(long arg0, boolean arg1)
	public abstract long consumerCount(String arg0)
	public abstract boolean waitForConfirms()
	public abstract boolean waitForConfirms(long arg0)
	public abstract long messageCount(String arg0)
	public abstract SelectOk txSelect()
	public abstract RollbackOk txRollback()
	public abstract CommitOk txCommit()
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, DeliverCallback arg3, CancelCallback arg4, ConsumerShutdownSignalCallback arg5)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, boolean arg3, boolean arg4, Map arg5, Consumer arg6)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, boolean arg3, boolean arg4, Map arg5, DeliverCallback arg6, CancelCallback arg7)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, boolean arg3, boolean arg4, Map arg5, DeliverCallback arg6, ConsumerShutdownSignalCallback arg7)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, boolean arg3, boolean arg4, Map arg5, DeliverCallback arg6, CancelCallback arg7, ConsumerShutdownSignalCallback arg8)
	public abstract String basicConsume(String arg0, boolean arg1, DeliverCallback arg2, ConsumerShutdownSignalCallback arg3)
	public abstract String basicConsume(String arg0, boolean arg1, DeliverCallback arg2, CancelCallback arg3)
	public abstract String basicConsume(String arg0, Consumer arg1)
	public abstract String basicConsume(String arg0, boolean arg1, DeliverCallback arg2, CancelCallback arg3, ConsumerShutdownSignalCallback arg4)
	public abstract String basicConsume(String arg0, boolean arg1, Map arg2, Consumer arg3)
	public abstract String basicConsume(String arg0, DeliverCallback arg1, CancelCallback arg2)
	public abstract String basicConsume(String arg0, DeliverCallback arg1, ConsumerShutdownSignalCallback arg2)
	public abstract String basicConsume(String arg0, DeliverCallback arg1, CancelCallback arg2, ConsumerShutdownSignalCallback arg3)
	public abstract String basicConsume(String arg0, boolean arg1, Consumer arg2)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, DeliverCallback arg3, ConsumerShutdownSignalCallback arg4)
	public abstract String basicConsume(String arg0, boolean arg1, Map arg2, DeliverCallback arg3, CancelCallback arg4, ConsumerShutdownSignalCallback arg5)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, Consumer arg3)
	public abstract String basicConsume(String arg0, boolean arg1, String arg2, DeliverCallback arg3, CancelCallback arg4)
	public abstract String basicConsume(String arg0, boolean arg1, Map arg2, DeliverCallback arg3, ConsumerShutdownSignalCallback arg4)
	public abstract String basicConsume(String arg0, boolean arg1, Map arg2, DeliverCallback arg3, CancelCallback arg4)
	public abstract RecoverOk basicRecover(boolean arg0)
	public abstract RecoverOk basicRecover()
	public abstract SelectOk confirmSelect()
	public abstract void queueDeleteNoWait(String arg0, boolean arg1, boolean arg2)
	public abstract CompletableFuture asyncCompletableRpc(Method arg0)
	public abstract void waitForConfirmsOrDie(long arg0)
	public abstract void waitForConfirmsOrDie()
	public abstract long getNextPublishSeqNo()
