----------------------
CompositeByteBuf
----------------------
	# 组合buf: public class CompositeByteBuf extends AbstractReferenceCountedByteBuf implements Iterable<ByteBuf> 


----------------------
this
----------------------
	public CompositeByteBuf(ByteBufAllocator alloc, boolean direct, int maxNumComponents)
	public CompositeByteBuf(ByteBufAllocator alloc, boolean direct, int maxNumComponents, ByteBuf... buffers)
	public CompositeByteBuf(ByteBufAllocator alloc, boolean direct, int maxNumComponents, Iterable<ByteBuf> buffers)

	public CompositeByteBuf addComponent(ByteBuf buffer)
	public CompositeByteBuf addComponents(ByteBuf... buffers)
	public CompositeByteBuf addComponents(Iterable<ByteBuf> buffers)
	public CompositeByteBuf addComponent(int cIndex, ByteBuf buffer)
	public CompositeByteBuf addComponent(boolean increaseWriterIndex, ByteBuf buffer)
	public CompositeByteBuf addComponents(boolean increaseWriterIndex, ByteBuf... buffers)
	public CompositeByteBuf addComponents(boolean increaseWriterIndex, Iterable<ByteBuf> buffers)
	public CompositeByteBuf addComponent(boolean increaseWriterIndex, int cIndex, ByteBuf buffer)
	public CompositeByteBuf addComponents(int cIndex, ByteBuf... buffers)
	public CompositeByteBuf addComponents(int cIndex, Iterable<ByteBuf> buffers)
	public CompositeByteBuf addFlattenedComponents(boolean increaseWriterIndex, ByteBuf buffer)
	public CompositeByteBuf removeComponent(int cIndex)
	public CompositeByteBuf removeComponents(int cIndex, int numComponents)
	public Iterator<ByteBuf> iterator()

	public List<ByteBuf> decompose(int offset, int length)
	public boolean isDirect()
	public boolean hasArray()
	public byte[] array()
	public int arrayOffset()
	public boolean hasMemoryAddress()
	public long memoryAddress()
	public int capacity()
	public CompositeByteBuf capacity(int newCapacity)
	public ByteBufAllocator alloc()
	public ByteOrder order() 
	public int numComponents()
	public int maxNumComponents()
	public int toComponentIndex(int offset)
	public int toByteIndex(int cIndex)
	public byte getByte(int index)
	public CompositeByteBuf getBytes(int index, byte[] dst, int dstIndex, int length)
	public CompositeByteBuf getBytes(int index, ByteBuffer dst)
	public CompositeByteBuf getBytes(int index, ByteBuf dst, int dstIndex, int length) 
	public int getBytes(int index, GatheringByteChannel out, int length) throws IOException
	public int getBytes(int index, FileChannel out, long position, int length)
	public CompositeByteBuf getBytes(int index, OutputStream out, int length) throws IOException
	public CompositeByteBuf setByte(int index, int value) 
	public CompositeByteBuf setShort(int index, int value)
	public CompositeByteBuf setMedium(int index, int value)
	public CompositeByteBuf setInt(int index, int value)
	public CompositeByteBuf setLong(int index, long value)
	public CompositeByteBuf setBytes(int index, byte[] src, int srcIndex, int length)
	public CompositeByteBuf setBytes(int index, ByteBuffer src)
	public CompositeByteBuf setBytes(int index, ByteBuf src, int srcIndex, int length)
	public int setBytes(int index, InputStream in, int length) throws IOException
	public int setBytes(int index, ScatteringByteChannel in, int length) throws IOException
	public int setBytes(int index, FileChannel in, long position, int length) throws IOException
	public ByteBuf copy(int index, int length) 
	public ByteBuf component(int cIndex)
	public ByteBuf componentAtOffset(int offset)
	public ByteBuf internalComponent(int cIndex) 
	public ByteBuf internalComponentAtOffset(int offset)
	public int nioBufferCount()
	public ByteBuffer internalNioBuffer(int index, int length) 
	public ByteBuffer nioBuffer(int index, int length)
	public ByteBuffer[] nioBuffers(int index, int length)
	public CompositeByteBuf consolidate()
	public CompositeByteBuf consolidate(int cIndex, int numComponents)
	public CompositeByteBuf discardReadComponents()
	public CompositeByteBuf discardReadBytes()
	public String toString()
	public CompositeByteBuf readerIndex(int readerIndex)
	public CompositeByteBuf writerIndex(int writerIndex)
	public CompositeByteBuf setIndex(int readerIndex, int writerIndex)
	public CompositeByteBuf clear()
	public CompositeByteBuf markReaderIndex()
	public CompositeByteBuf resetReaderIndex()
	public CompositeByteBuf markWriterIndex()
	public CompositeByteBuf resetWriterIndex()
	public CompositeByteBuf ensureWritable(int minWritableBytes)
	public CompositeByteBuf getBytes(int index, ByteBuf dst)
	public CompositeByteBuf getBytes(int index, ByteBuf dst, int length)
	public CompositeByteBuf getBytes(int index, byte[] dst)
	public CompositeByteBuf setBoolean(int index, boolean value)
	public CompositeByteBuf setChar(int index, int value)
	public CompositeByteBuf setFloat(int index, float value)
	public CompositeByteBuf setDouble(int index, double value)
	public CompositeByteBuf setBytes(int index, ByteBuf src)
	public CompositeByteBuf setBytes(int index, ByteBuf src, int length)
	public CompositeByteBuf setBytes(int index, byte[] src) 
	public CompositeByteBuf setZero(int index, int length)
	public CompositeByteBuf readBytes(ByteBuf dst)
	public CompositeByteBuf readBytes(ByteBuf dst, int length)
	public CompositeByteBuf readBytes(ByteBuf dst, int dstIndex, int length)
	public CompositeByteBuf readBytes(byte[] dst)
	public CompositeByteBuf readBytes(byte[] dst, int dstIndex, int length)
	public CompositeByteBuf readBytes(ByteBuffer dst)
	public CompositeByteBuf readBytes(OutputStream out, int length) throws IOException
	public CompositeByteBuf skipBytes(int length) 
	public CompositeByteBuf writeBoolean(boolean value)
	public CompositeByteBuf writeByte(int value)
	public CompositeByteBuf writeShort(int value) 
	public CompositeByteBuf writeMedium(int value)
	public CompositeByteBuf writeInt(int value) 
	public CompositeByteBuf writeLong(long value)
	public CompositeByteBuf writeChar(int value)
	public CompositeByteBuf writeFloat(float value) 
	public CompositeByteBuf writeDouble(double value)
	public CompositeByteBuf writeBytes(ByteBuf src)
	public CompositeByteBuf writeBytes(ByteBuf src, int length)
	public CompositeByteBuf writeBytes(ByteBuf src, int srcIndex, int length)
	public CompositeByteBuf writeBytes(byte[] src) 
	public CompositeByteBuf writeBytes(byte[] src, int srcIndex, int length)
	public CompositeByteBuf writeBytes(ByteBuffer src) 
	public CompositeByteBuf writeZero(int length)
	public CompositeByteBuf retain(int increment)
	public CompositeByteBuf retain()
	public CompositeByteBuf touch()
	public CompositeByteBuf touch(Object hint)
	public ByteBuffer[] nioBuffers()
	public CompositeByteBuf discardSomeReadBytes()
	public ByteBuf unwrap()


